### ISSUE TITLE
This repo's master and maven repository are not at the same version

### ISSUE THREAD

**Issue by Pranava29** [jillesvangurp/geogeometry#11]
Hi,
Can you please push the latest master to maven repository? There are some fixes in line cross utility which are not available in 2.11. 

https://mvnrepository.com/artifact/com.jillesvangurp/geogeometry/2.11

**Comment by jillesvangurp** [comment]
Thanks. I updated the readme with instructions for getting the latest tag from jitpack.

**Comment by cr0man** [comment]
Mary Christmas, Jilles!
