### ISSUE TITLE
lineCross function is resulting in a false positive

### ISSUE THREAD

**Issue by Pranava29** [jillesvangurp/geogeometry#12]
Hi,
The following line segments do not actually intersect but the ```lineCross``` utility is returning a false positive.
```
{
        "type": "LineString",
        "coordinates": [
          [
            -71.1884310511,
            42.3219864254
          ],
          [
            -71.1884310511,
            42.321998793
          ]
        ]
      }
```
```
{
        "type": "LineString",
        "coordinates": [
          [
            -71.1884310515,
            42.3221529806
          ],
          [
            -71.1884310517,
            42.3222331303
          ]
        ]
      }
```
<img width="1680" alt="screen shot 2018-12-27 at 12 05 54 am" src="https://user-images.githubusercontent.com/10139286/50454160-b7b8c100-096b-11e9-9ce9-004ec3d895f2.png">

**Comment by Pranava29** [comment]
@jillesvangurp , any update on this? Please let me know if you need any more analysis information.

**Comment by jillesvangurp** [comment]
I finally looked into this, the lines actually do intersect but the segments do not.
- line 1 is vertical
- line2 intersects line1 at -71.1884310511,42.32199266925454
- 42.32199266925454 is in between 42.3219864254 and 42.321998793, this is why the check passes
- however, this is NOT in between 42.3221529806 and 42.3222331303 of line2 so the intersection point is outside of that. This is the bug and we need to check both line segments. Pushing a fix soon.
