### ISSUE TITLE
Bbox lat/lng mixup

### ISSUE THREAD

**Issue by Falx** [jillesvangurp/geogeometry#13]
In https://github.com/jillesvangurp/geogeometry/blob/0fb0e09ad9ec2c066306f5cf995fbc5a12ac7018/src/main/java/com/jillesvangurp/geo/GeoGeometry.java#L461

You say you return [minlat, maxlat, minlon, maxlon] while in reality it is [maxlat, minlat, maxlon, minlon].

**Comment by jillesvangurp** [comment]
You are right; thanks for letting me know. FYI, I'm currently porting this library to Kotlin.

**Comment by jillesvangurp** [comment]
I updated the documentation in the Kotlin port. In the process I noticed that the way I do bounding boxes is slightly different than what GeoJson does. I may end up fixing that soon (#15).
