### ISSUE TITLE
Version 3.3.8 build with Java 21

### ISSUE THREAD

**Issue by jvdadda** [jillesvangurp/geogeometry#39]
It seems that the last version (3.3.8) is build with Java 21, that breaks all applications using a previous version of it :
```
Caused by:
        java.lang.UnsupportedClassVersionError: com/jillesvangurp/geojson/FeatureCollection has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
```

Can you rebuild it with the smallest version possible to be usable easily ?

Thanks a lot

**Comment by jillesvangurp** [comment]
I added jvmTarget 11; can you give 3.3.9 a try?

**Comment by jvdadda** [comment]
Perfect, it works, thanks !
