### ISSUE TITLE
Missing feature property: "id". Deserialisation fails when id is present

### ISSUE THREAD

**Issue by ninovanhooff** [jillesvangurp/geogeometry#40]
Per the spec: https://datatracker.ietf.org/doc/html/rfc7946#section-3.2

A Feature may have an "id", as either a string or number. I would then expect geogeometry to parse it as a string, leaving it up to the implementer to convert it to a number if needed.

However, kotlinx-serialization fails when my features have an id:

```
{
  "features": [
    {
      "id": "sme1d0ae0f",
      "type": "Feature",
      "coordinates": [4.884864, 52.360325]}
        "type": "Point"
      },
      "properties": {
        "name": "WC",
        "links": "[]",
        "rotation": 0.6918614135181254,
        "baseType": "POI",
        "subType": "WcMarker",
        "floor": -1
      }
    },
```

A workaround would be to parse like this:

```
Json {
      ignoreUnknownKeys = true
    }.decodeFromStream<FeatureCollection>(inputStream)
```

But I'm losing the id in the process. That forces me to pre-process / generate the json in such a way as to add the id to the `properties`

### Expected
The `id` is available as a property of `Feature`

**Comment by jillesvangurp** [comment]
Thanks for reporting.

Have a look at this:

https://github.com/jillesvangurp/kotlinx-serialization-extensions/blob/main/src/commonMain/kotlin/com/jillesvangurp/serializationext/defaults.kt

Kotlinx.serialization defaults are terrible for parsing. These are the defaults I use pretty much everywhere. 

But you are right and I'll add the id field as it is common enough with geojson.

**Comment by ninovanhooff** [comment]
Hey there, I sure appreciate the quick reply and decisive action!

I see that you have overridden equals and hashcode despite it being a data class. You'll have your reasons, but I think two features with differing ids should not be equal, and thus the id should also be considered in those two methods?
